### ISSUE TITLE
关于源码的公布问题

### ISSUE THREAD

**Issue by BeiMingYy** [YangXiaocui1215/MGNNS#2]
您好，我阅读了您在ACL2021上的工作，觉得很有启发，但是对于论文中的一些细节我有一些疑问，请问您什么时候可以公布源码呢？谢谢，我的邮箱是823275212@qq.com

**Comment by AIYA-ai** [comment]
你好，你复现了嘛，能把源码发我一份嘛，我的邮箱是1342965363@qq.com
