### ISSUE TITLE
Sentiment Embedding Matrix的获取

### ISSUE THREAD

**Issue by doubibobo** [YangXiaocui1215/MGNNS#6]
老师您好，拜读了您的工作之后，我深受启发，但有一个问题我没有想明白，还请老师指教！

在图像视觉特征与GCN Place融合之后，您进行了一个`Emotion-aware Multihead-Attention`的运算，利用到了`Sentiment Embedding Matrix`。由您的如下代码：https://github.com/YangXiaocui1215/MGNNS/blob/18dc6b7348ba86eba055620ca3637adf3dc55eed/models/Multi_GCN_Multihead_att.py#L503
https://github.com/YangXiaocui1215/MGNNS/blob/18dc6b7348ba86eba055620ca3637adf3dc55eed/models/Multi_GCN_Multihead_att.py#L462
https://github.com/YangXiaocui1215/MGNNS/blob/18dc6b7348ba86eba055620ca3637adf3dc55eed/models/Multi_GCN_Multihead_att.py#L26
可知：这个matrix来源于样本标签的`glove embedding`，相当于一种已知知识。 可是我理解这种已知知识可以用于训练集，验证集和测试集并不可用呀……

换言之：对于模型而言，如何获取验证集和测试集的`Sentiment Embedding Matrix`？

您并没有给出`data/glove/tumblr_label_glove.pkl`文件，因此在这一点上我非常困惑，希望得到老师的解答。如果我理解有误，还请指正！

**Comment by doubibobo** [comment]
难道是我想复杂了

glove_label_embedding仅仅是标签的embedding，并不涉及样本的真实标签？

比如在极性分类中是positive/neutral/negative的embedding？

**Comment by YangXiaocui1215** [comment]
> 难道是我想复杂了
> 
> `glove_label_embedding`仅仅是标签的`embedding`，并不涉及样本的真实标签？
> 
> 比如在极性分类中是`positive/neutral/negative`的`embedding`？

Yes. 它只是简单的标签嵌入，不涉及数据集样例的标签分布。只和数据集有关。

**Comment by doubibobo** [comment]
明白了，谢谢您
